# Generated by Django 4.0.6 on 2022-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0029_alter_properties_slug_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
