# Generated by Django 4.0.6 on 2022-10-17 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0031_tours_alter_properties_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties'),
        ),
    ]
