# Generated by Django 4.0.6 on 2022-10-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0032_tours_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='mark_as_span',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tours',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
