# Generated by Django 4.0.6 on 2022-10-18 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseListing', '0033_tours_mark_as_span_tours_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='approved_by_admin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='available_rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='security_deposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        # migrations.AlterField(
        #     model_name='properties',
        #     name='slug',
        #     field=models.SlugField(blank=True, null=True, unique=True),
        # ),
        migrations.AlterField(
            model_name='properties',
            name='units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
