# Generated by Django 4.0.6 on 2022-10-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0037_alter_vacatenotice_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacatenotice',
            name='vacated',
            field=models.BooleanField(default=False),
        ),
    ]
