# Generated by Django 4.0.6 on 2022-10-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0038_vacatenotice_vacated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='house',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tenant',
        ),
        # migrations.AlterField(
        #     model_name='properties',
        #     name='slug',
        #     field=models.SlugField(blank=True, null=True, unique=True),
        # ),
    ]
