# Generated by Django 4.0.6 on 2022-10-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0040_morgageleads_property_relocationleads'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocationleads',
            name='current_town',
            field=models.CharField(blank='True', max_length=100, null=True),
        ),
    ]
