# Generated by Django 4.0.6 on 2022-10-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0041_relocationleads_current_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocationleads',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relocationleads',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
