# Generated by Django 4.0.6 on 2022-11-08 08:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0042_relocationleads_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        # migrations.AlterField(
        #     model_name='properties',
        #     name='slug',
        #     field=models.SlugField(blank=True, null=True, unique=True),
        # ),
    ]
